version: "2"

networks:
  network:


services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: "472"
    ports:
      - 3000:3000
    networks:
      - network
    volumes:
      - ./grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/influxdb.pem
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/influxdb.key
    networks:
      - network
    volumes:
      - ./influxdb-volume:/var/lib/influxdb
      - ./ssl:/etc/ssl:ro
