version: "2"

networks:
  tig_stack_network:


services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - tig_stack_network
    volumes:
      - ./grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    networks:
      - tig_stack_network
    volumes:
      - ./influxdb-volume:/var/lib/influxdb
