{
 "title": "Docker Dashboard",
 "description": "Detailed dashboard for DOCKERS from telegraf and InfluxDB metrics",
 "tags": [
  "influxdb",
  "telegraf",
  "docker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SELECT \"host\" FROM (SELECT last(\"uptime\") AS \"mean_uptime\" FROM \"system\" WHERE  $timeFilter GROUP BY \"host\")"
   },
   {
    "name": "Container",
    "label": "Container",
    "query": "SELECT \"container_name\" FROM (SELECT distinct(\"container_id\") FROM \"docker_container_status\" WHERE $timeFilter GROUP BY \"container_name\")"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Docker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Paused Docker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Stopped Docker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Docker Images",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "container_status" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker_container_status",
     "select": [
      [
       { "params": [ "container_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "Container ID" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Docker Hosts Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Running" ], "type": "alias" }
      ],
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Paused" ], "type": "alias" }
      ],
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Stopped" ], "type": "alias" }
      ],
      [
       { "params": [ "n_images" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Images" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage % by Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem Usage % by Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name RX traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_container_name TX traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name IO_write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_container_name IO_read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Details for $Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "Container",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU for $Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Usage [%]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory for $Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Usage [%]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "IO for $Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "IO service recursive read",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_read"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "IO service recursive write",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_write"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network for $Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Recived",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      },
      {
       "alias": "Transmited",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$Container$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}